### ISSUE TITLE
Add compatibility with Comforts hammocks

### ISSUE THREAD

**Issue by teleheel** [Steveplays28/realisticsleep#23]
Sleeping in hammocks from the [Comforts](https://modrinth.com/mod/comforts) mod actually works with time speeding up. However the sleep message still says `x/y players are sleeping through this night (time until dawn: z)`. Would it be possible to have it say `x/y players are sleeping through this day(time until dusk: z)` instead when sleeping in the day?

**Comment by Steveplays28** [comment]
Hey, good to know that Comforts works with my mod, but I'm not sure how to handle this case.
Can't you sleep in a hammock even during the night, or am I misremembering that?

**Comment by ChromaPIE** [comment]
@Steveplays28 No the actual behavior is working great. Time passes when player's sleeping in hammocks, and it do shows the countdown to the night with zero problem. It's only an issue with the displayed text _through this night_, but players are actually _day_dreaming, so it feels wrong.

So this request is about making the displayed text _through this day_ instead of _through this night_ when players are sleeping in hammocks from Comfort during the day.

Also it will be a bit imbalanced cuz players can literally speed everything up 24/7 with both vanilla beds and Comfort hammocks. So imma add one more request here (if it's technically possible): a config option to disable speed-up feature when it comes to hammocks, time will still elapse faster but stuff like crops and tile-entities won't get sped up, so players can only use hammocks as a tool to pass the day quicker but not another torcherino in the daytime.

**Comment by Steveplays28** [comment]
Thanks for the info, I'll take a look at implementing your ideas at some point. Currently working on other projects since I got this mod in a stable state, but I'll put it on the todo list.
No promises though.

**Comment by Steveplays28** [comment]
This has been fixed in `v1.8.0`.
Have fun playing!

**Comment by teleheel** [comment]
Awesome!
