### ISSUE TITLE
After sleeping, the next weather change will always be a thunderstorm

### ISSUE THREAD

**Issue by Crossover661** [Steveplays28/realisticsleep#35]
When sleeping, the weather is set to clear, which always results in thunderTime being less than rainTime. This causes the weather to go straight from clear to thunder, skipping rain. In my survival world I experienced four thunderstorms in a span of about 5 days.

**Comment by Steveplays28** [comment]
Huh, that's an odd issue. Never noticed that while playing myself, I'll have a look sometime next week along with the other issues.

**Comment by sanjays661** [comment]
There is a bug that when using "/weather clear", the next weather change is always a thunderstorm. You can test it in vanilla Minecraft using "/weather clear 1s" - a thunderstorm will start immediately after. https://bugs.mojang.com/browse/MC-108806

This bug happens for the same reason. Suggestion: in ServerWorldMixin.java instead of using setClearWeatherTime, use setRainTime() and setThunderTime() - making sure that the value in setThunderTime is always greater than setRainTime.

Also, the mod wakes up players really early - at time 23250 (5:15 am), so early that skeletons and zombies don't burn in the sunlight until several seconds later. There should be a configuration in the world settings to set the wake-up time (defaulting to 0 or 6 am), as well as the latest and earliest times one can go to bed.

**Comment by Steveplays28** [comment]
Ah, didn't know that was a vanilla bug. Thanks, I'll have a look at implementing your solution!

The second issue you described is due to a workaround I'm doing to wake up all the players. I still have to look into fixing the issue I was having with it, so I can remove the workaround. See #20.

**Comment by sanjays661** [comment]
A better solution: use the resetWeather() method instead of setClearWeatherTime.

**Comment by Steveplays28** [comment]
This has been released in `v1.8.0`, there's now a 50% chance of a thunderstorm appearing, by either incrementing or decrementing a time unit to thunder.
Have fun playing!
